# Done to increase the memory available to gradle.
org.gradle.jvmargs=-Xmx4G
org.gradle.parallel=true

# Fabric Properties
# check these on https://fabricmc.net/develop
minecraft_version=1.21.1
yarn_mappings=1.21.1+build.3
loader_version=0.17.2
loom_version=1.11-SNAPSHOT

# Mod Properties
mod_version=1.0.2
maven_group=com.sp
archives_base_name=destroying-minecraft-early-access

# Dependencies
fabric_version=0.116.6+1.21.1
veil_version=2.3.2
molang_compiler_version=3.1.1.19
glsl_processor_version=0.2.3
imgui_version=1.88.0
sodium_version=0.6.13
cca_version=6.1.2
midnightlib_version=1.6.9+1.21-fabric
modmenu_version=11.0.3